# This is the config to use for Mooring/CTD merges. CTD file can be .cnv or .nc

# Machine Readable File information - this is used to make the QAQC (AKA the Quagmire)
machine_readable_info:
  machine_readable_files: 
    - /Users/zalmanek/Development/PMEL-OME-OCNMS/Brynn_OCNMS_data_reorganized/CTD_data/2021_Aug_OCNMS_TH042/machineReadableFixed_OC0821.csv
    - /Users/zalmanek/Development/PMEL-OME-OCNMS/Brynn_OCNMS_data_reorganized/CTD_data/2021_Oct_OCNMS_TH042/machineReadableFixed_OC1021.csv
    - /Users/zalmanek/Development/PMEL-OME-OCNMS/Brynn_OCNMS_data_reorganized/CTD_data/2022_Aug_OCNMS_TH042/machineReadableFixed_OC0822.csv
    - /Users/zalmanek/Development/PMEL-OME-OCNMS/Brynn_OCNMS_data_reorganized/CTD_data/2022_July_OCNMS_TH042/machineReadableFixed_OC0722.csv
    - /Users/zalmanek/Development/PMEL-OME-OCNMS/Brynn_OCNMS_data_reorganized/CTD_data/2022_Jun_OCNMS_TH042/machineReadableFixed_OC0622.csv
    - /Users/zalmanek/Development/PMEL-OME-OCNMS/Brynn_OCNMS_data_reorganized/CTD_data/2022_Sept_OCNMS_TH042/machineReadableFixed_OC0922.csv
    - /Users/zalmanek/Development/PMEL-OME-OCNMS/Brynn_OCNMS_data_reorganized/CTD_data/2023_July_OCNMS_TH042/machineReadableFixed_OC0723.csv
    - /Users/zalmanek/Development/PMEL-OME-OCNMS/Brynn_OCNMS_data_reorganized/CTD_data/2023_Jun_OCNMS_TH042/machineReadableFixed_OC0623.csv
  station_col: 'Cast' # Must match what's in the ctd_data (This seems to vary - Station would be normal, but someimtes for Mooring/PPS it varies). Must be teh same for all the machine readable files

# Mooring data 
mooring_info: # Takes a list of .mat files (in case we want to aggregate a bunch together. Right now doing OCNMS 2021-2023)
  mooring_data_dir: /Users/zalmanek/Development/PMEL-OME-OCNMS/Brynn_OCNMS_data_reorganized/mooring_data/
  sensors: #  A list of sensors to grab data from (shoudl match the sensor name in the variables in the .mat files)
    - CTPO

# NetCDF or .CNV info (AKA the CTD data) The directory where all the net cdf files live with the station_ids in the folder names and file names
ctd_data:
  # net_cdf_dir: /Users/zalmanek/Development/PMEL-OME-OCNMS/Ella_combined_20250530/OCNMS_ctd_data_Ella/data/Olympic_Coast_National_Marine_Sanctuary_CTD_Data_2005_2023/netcdf_files/binned_profiles
  ros_dir: /Users/zalmanek/Development/PMEL-OME-OCNMS/Brynn_OCNMS_data_reorganized/CTD_data/
  ctd_quag_merge_tolerance: '1.2 days' # should be in the form of 'pd.Timedelta('1h')'. The time tolerance to merge CTD and quagmire. Leave blank if just want to find closes datetime and have no tolerance range.
  julian_day_convention: '0 day' # Choose between either '0 day' or '1 day', meaning '0 day' = Day 1 starts on julian Day 0.0 (JD 1.0 is Jan 2nd). '1 day' = Day 1 starts at Julian Day 1.0 (JD=1.0 is January 1st)

# Assumes will be .nc file right now. Setting up to take multiple files even though for OCNMS, only TH042 was used
ocean_model_data:
  model_nc_files:
    - /Users/zalmanek/Development/PMEL-OME-OCNMS/Ella_combined_20250530/Reed-Thesis-Copepod-Populations/LiveOceanTH042_2021_2023.nc
    - /Users/zalmanek/Development/PMEL-OME-OCNMS/Brynn_OCNMS_data_reorganized/CE042_live_ocean_mode/OCNMS_cas7_t0_x4b_lowpass_2013_2023 2/CE042_2013.01.01_2023.12.31.nc
  depth_variable_name: z_rho # The name of the variable that holds the physical depth information (e.g. z_rho)
  time_dim_name: ocean_time # The name of the time dimension in the ocean model data
  